export const arr = [
  {
    id: 1,
    check: false,
    name: "Jenny",
    surname: "Chan",
    age: "54",
    addres: "3 waterfoot road",
    email: "jenny.chan@email.com",
    edit: false,
  },
  {
    id: 2,
    check: false,
    name: "Jeremy",
    surname: "Clark",
    age: "22",
    addres: "11 lesly road",
    email: "jeremy.clark@email.com",
    edit: false,
  },
  {
    id: 3,
    check: false,
    name: "Jessica",
    surname: "Afsn",
    age: "43",
    addres: "1 test road",
    email: "jessica.warren@email.com",
    edit: false,
  },
  {
    id: 4,
    check: false,
    name: "Tony ",
    surname: "Frank",
    age: "45",
    addres: "99 blue acres",
    email: "tony.frank@email.com",
    edit: false,
  },
  {
    id: 5,
    check: false,
    name: "Jeremy ",
    surname: "Clark",
    age: "34",
    addres: "1 test road",
    email: "jeremy.clark@email.com",
    edit: false,
  },
  {
    id: 6,
    check: false,
    name: "Raymond ",
    surname: "Edwards",
    age: "32",
    addres: "f test road",
    email: "test@test.com",
    edit: false,
  },
];
